AllCops:
  NewCops: enable

Bundler/OrderedGems:
  Enabled: false

Layout/LineLength:
  Exclude:
    - db/seeds.rb

Metrics/BlockNesting:
  Exclude:
    - app/controllers/users_controller.rb

Metrics/ClassLength:
  Exclude:
    - app/controllers/users_controller.rb

Style/Documentation:
  Enabled: false

Style/NumericLiterals:
  Exclude:
    - db/schema.rb
